
services:
  keycloak:
    image: ${KEYCLOAK_IMAGE}
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_HTTP_RELATIVE_PATH=${KEYCLOAK_HTTP_RELATIVE_PATH}
      - KEYCLOAK_PRODUCTION=${KEYCLOAK_PRODUCTION}
      - KEYCLOAK_DATABASE_HOST=${KEYCLOAK_DATABASE_HOST}
      - KEYCLOAK_DATABASE_PORT_NUMBER=${KEYCLOAK_DATABASE_PORT_NUMBER}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DATABASE_NAME}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DATABASE_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - KEYCLOAK_DATABASE_SCHEMA=${KEYCLOAK_DATABASE_SCHEMA}
    ports:
      - ${KEYCLOAK_PORTS_HTTP}
      - ${KEYCLOAK_PORTS_HTTPS}
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - keycloak_network
  postgresql:
    image: ${POSTGRESQL_IMAGE}
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgresql_data:/bitnami/postgresql:rw
    ports:
      - ${POSTGRESQL_PORTS_HTTP}
    networks:
      - keycloak_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgresql_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge