
services:
  keycloak:
    image: bitnami/keycloak:26.1.3
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_HTTP_RELATIVE_PATH=${KEYCLOAK_HTTP_RELATIVE_PATH}
      - KEYCLOAK_PRODUCTION=${KEYCLOAK_PRODUCTION}
      - KEYCLOAK_DATABASE_HOST=${KEYCLOAK_DATABASE_HOST}
      - KEYCLOAK_DATABASE_PORT_NUMBER=${KEYCLOAK_DATABASE_PORT_NUMBER}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DATABASE_NAME}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DATABASE_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - KEYCLOAK_DATABASE_SCHEMA=${KEYCLOAK_DATABASE_SCHEMA}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - keycloak_network
  postgresql:
    image: bitnami/postgresql:17.4.0
    container_name: postgresql
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgresql_data:/bitnami/postgresql:rw
    ports:
      - "5432:5432"
    networks:
      - keycloak_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgresql_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge